/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoSoftware;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emerson
 */
public class formFechamentoDeCaixa extends javax.swing.JFrame {
    int ITEM = 1;
    private Connection con;

    /**
     * Creates new form formFechamentoDeCaixa
     */
    public formFechamentoDeCaixa() {
        initComponents();
        btnCancelar.setEnabled(false);
        btnSair.setEnabled(false);
        btnSalvar.setEnabled(false);
        carregarImagens();
    }
 public void carregarImagens(){
     ImageIcon inserir = new ImageIcon("C:/Imagem/09_Inserir.png");
     ImageIcon editar = new ImageIcon("C:/Imagem/06_Editar.png");
     ImageIcon excluir = new ImageIcon("C:/Imagem/07_Excluir.png");
     ImageIcon pesquisar = new ImageIcon("C:/Imagem/11_Lupa.png");
     ImageIcon excel = new ImageIcon("C:/Imagem/03_Excel.png");
     ImageIcon sair = new ImageIcon("C:/Imagem/08_Fechar.png");
     ImageIcon Limpar = new ImageIcon("C:/Imagem/05_Clear.png");
     ImageIcon Atualizar = new ImageIcon("C:/Imagem/13_Atualizar.png");
     ImageIcon Cadastrar = new ImageIcon("C:/Imagem/14_Cadastrar.png");
     
        btnSalvar.setIcon(inserir);
        btnSair.setIcon(sair);
        btnCancelar.setIcon(Limpar);
        btnBuscar.setIcon(pesquisar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidadeProduto = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaReceitas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotaldeProdutos = new javax.swing.JLabel();
        txtTotaldeReceitas = new javax.swing.JLabel();
        txtSobrasEFaltas = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fechamento de Caixa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fechamento de Caixa"));

        jLabel1.setText("Data");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataKeyPressed(evt);
            }
        });

        btnBuscar.setText("Consultar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Código", "Produto", "Quantidade", "Total"
            }
        ));
        jScrollPane1.setViewportView(TabelaProdutos);
        if (TabelaProdutos.getColumnModel().getColumnCount() > 0) {
            TabelaProdutos.getColumnModel().getColumn(0).setMinWidth(50);
            TabelaProdutos.getColumnModel().getColumn(0).setMaxWidth(50);
            TabelaProdutos.getColumnModel().getColumn(1).setMinWidth(50);
            TabelaProdutos.getColumnModel().getColumn(1).setMaxWidth(50);
            TabelaProdutos.getColumnModel().getColumn(3).setMinWidth(80);
            TabelaProdutos.getColumnModel().getColumn(3).setMaxWidth(80);
            TabelaProdutos.getColumnModel().getColumn(4).setMinWidth(80);
            TabelaProdutos.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jLabel2.setText("Quantidade Total");

        jLabel3.setText("Valor Total");

        txtQuantidadeProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtQuantidadeProduto.setForeground(new java.awt.Color(255, 0, 0));

        txtValorProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtValorProduto.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimento", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TabelaReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Documento", "Descrição", "Total"
            }
        ));
        jScrollPane2.setViewportView(TabelaReceitas);
        if (TabelaReceitas.getColumnModel().getColumnCount() > 0) {
            TabelaReceitas.getColumnModel().getColumn(0).setMinWidth(50);
            TabelaReceitas.getColumnModel().getColumn(0).setMaxWidth(50);
            TabelaReceitas.getColumnModel().getColumn(1).setMinWidth(80);
            TabelaReceitas.getColumnModel().getColumn(1).setMaxWidth(80);
            TabelaReceitas.getColumnModel().getColumn(3).setMinWidth(80);
            TabelaReceitas.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel4.setText("Total de Produtos");

        jLabel5.setText("Total de Receitas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Sobras e Faltas");

        txtTotaldeProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotaldeProdutos.setForeground(new java.awt.Color(255, 0, 0));

        txtTotaldeReceitas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotaldeReceitas.setForeground(new java.awt.Color(255, 0, 0));

        txtSobrasEFaltas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSobrasEFaltas.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotaldeReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotaldeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSobrasEFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtTotaldeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtSobrasEFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotaldeReceitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Receitas", jPanel3);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       consultar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void consultar(){
         double produto = 0,receita = 0;
        try {
            this.con = database.getConnection();
            
            Produto PRO = new Produto();
            
            PreparedStatement busca = con.prepareStatement("select * from cpro order by pro_cod");
            
            ResultSet rs = busca.executeQuery();
            
            while(rs.next()){
                PRO.codigo = rs.getString("PRO_COD");
                PRO.descricao = rs.getString("PRO_DES");
                try {
                    this.con = database.getConnection();

                    String PROCodigo = PRO.descricao;


                    PreparedStatement posted = con.prepareStatement("select sum(itmqtd) as QTD,sum(itmvlrtot) as TOTAL from cteitm,ctenfe where itmnum = nfenum and nfenum > 0 and nfeope = '065' and itmcodpro = '"+PRO.codigo+"' and nfedat = '"+txtData.getText()+"'");

                    ResultSet rs1 = posted.executeQuery();

                    rs1.next(); 
                        String Quantidade = rs1.getString("QTD");
                        String Total = rs1.getString("TOTAL");

                        DefaultTableModel val = (DefaultTableModel) TabelaProdutos.getModel();
                     if(Total == null){
                         // produtos em branco
                      } else{
                         String Item = "" + ITEM;
                         val.addRow(new String[]{Item,PRO.codigo,PRO.descricao,Quantidade,Total});
                         
                     }
                             

                } catch (Exception ex) {
                    Logger.getLogger(formCadastraProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                int qtd=0;
                double countpro=0;
            for (int i=0; i<=TabelaProdutos.getRowCount()-1;i++) {
                countpro+=Double.parseDouble(TabelaProdutos.getValueAt(i, 4).toString());
                qtd+=Integer.parseInt(TabelaProdutos.getValueAt(i, 3).toString());
            }
            String TotalGeral = "" + countpro; 
            produto = countpro;
            String QuantidadeTotal = "" + qtd;
            txtValorProduto.setText(TotalGeral);
            txtTotaldeProdutos.setText(TotalGeral);
            txtQuantidadeProduto.setText(QuantidadeTotal);
            }
        } catch (Exception ex) {
            Logger.getLogger(formFechamentoDeCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int num = 0;
        try {
            this.con = database.getConnection();
            
            PreparedStatement buscaDoc = con.prepareStatement("select * from docrec");
            
            ResultSet rs = buscaDoc.executeQuery();
            
            while(rs.next()){
                 String Documento = rs.getString("docdoc");
                 String Nome = rs.getString("docdes");
                 try {
                   this.con = database.getConnection();

                   Grupo_Produto PRO = new Grupo_Produto();

                   String PROCodigo = PRO.descricao;

                  
                       PreparedStatement posted = con.prepareStatement("select sum(nfevlrtot) as TOTAL from ctenfe,docrec where nferec = docdoc and nfeope = '065' and nferec = '"+Documento+"' and nfedat = '"+txtData.getText()+"'");

                       ResultSet rs1 = posted.executeQuery();

                       rs1.next();
                       String Total = rs1.getString("TOTAL");
            
                 DefaultTableModel val = (DefaultTableModel) TabelaReceitas.getModel();
                 if(Total == null){
                     // Documentos em branco
                 }else{
                     String Item = "" + ITEM;
                     val.addRow(new String[]{Item,Documento,Nome,Total});
                 }

               } catch (Exception ex) {
                   Logger.getLogger(formCadastraProduto.class.getName()).log(Level.SEVERE, null, ex);
               }
               num = 1;
            }
           try {
            this.con = database.getConnection();
            PreparedStatement busca1 = con.prepareStatement("select * from docsan where sandat = '"+txtData.getText()+"'");
                    ResultSet rs2 = busca1.executeQuery();
                    while(rs2.next()){
                        String Documento= rs2.getString("sandoc");
                        String Nome = rs2.getString("sandes");
                         PreparedStatement busca2 = con.prepareStatement("select sum(sanvlr) as TOTAL from docsan where sandat = '"+txtData.getText()+"'");
                         ResultSet rs3 = busca2.executeQuery();
                         rs3.next();
                        String Total = rs3.getString("TOTAL");

                        String Item = "" + ITEM;
                        DefaultTableModel val = (DefaultTableModel) TabelaReceitas.getModel();
                        val.addRow(new String[]{Item,Documento,"SANGRIAS",Total});   
                    }
               } catch (Exception ex) {
               //    Logger.getLogger(formCadastraProduto.class.getName()).log(Level.SEVERE, null, ex);
               }  
           int qtd=0;
                double countrec=0;
            for (int i=0; i<=TabelaReceitas.getRowCount()-1;i++) {
                countrec+=Double.parseDouble(TabelaReceitas.getValueAt(i, 3).toString());
            }
            String TotalReceitas = "" + countrec;
            receita = countrec;
            txtTotaldeReceitas.setText(TotalReceitas);
            
            if (num == 0) JOptionPane.showMessageDialog(null, "NÃO FOI ENCONTRADO DADOS PARA PARÂMETROS INFORMADOS!");
            btnCancelar.setEnabled(true);
            btnSair.setEnabled(true);
            btnSalvar.setEnabled(true);
            double SobrasFaltas = produto - receita;
            String sobrasefaltas = "" + SobrasFaltas;
            txtSobrasEFaltas.setText(sobrasefaltas);
        } catch (Exception ex) {
            Logger.getLogger(formRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        ITEM++;       
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtData.setText("");
        txtQuantidadeProduto.setText("");
        txtSobrasEFaltas.setText("");
        txtTotaldeProdutos.setText("");
        txtTotaldeReceitas.setText("");
        txtValorProduto.setText("");
        DefaultTableModel val = (DefaultTableModel) TabelaProdutos.getModel();
        int codigo = TabelaProdutos.getRowCount();
        for(int x=codigo-1 ; x>=0 ; x--){
            val.removeRow(x);
        }
        DefaultTableModel val1 = (DefaultTableModel) TabelaReceitas.getModel();
        int codigo1 = TabelaReceitas.getRowCount();
        for(int x=codigo1-1 ; x>=0 ; x--){
            val1.removeRow(x);
        }
        txtData.requestFocus();
        btnCancelar.setEnabled(false);
        btnSair.setEnabled(false);
        btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            consultar();
        }
    }//GEN-LAST:event_txtDataKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFechamentoDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFechamentoDeCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JTable TabelaReceitas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JLabel txtQuantidadeProduto;
    private javax.swing.JLabel txtSobrasEFaltas;
    private javax.swing.JLabel txtTotaldeProdutos;
    private javax.swing.JLabel txtTotaldeReceitas;
    private javax.swing.JLabel txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
