/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoSoftware;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Emerson
 */

public class formDocumentoSangrias extends javax.swing.JFrame {
 String Caso;
 String Caso2;
    private Connection con;
    
    /**
     * Creates new form formCadastraGrupo
     */
    public formDocumentoSangrias() {
        initComponents();
        txtDescricao.setDocument(new SoLetrasMaiusculas());
        txtDocumento.setDocument(new SoLetrasMaiusculas());
       // this.setLocationRelativeTo(null);//Centralizar Jframe
        txtDocumento.requestFocus();
        carregarImagens();


    }
    public void carregarImagens(){
     ImageIcon inserir = new ImageIcon("C:/Imagem/09_Inserir.png");
     ImageIcon editar = new ImageIcon("C:/Imagem/06_Editar.png");
     ImageIcon excluir = new ImageIcon("C:/Imagem/07_Excluir.png");
     ImageIcon pesquisar = new ImageIcon("C:/Imagem/11_Lupa.png");
     ImageIcon excel = new ImageIcon("C:/Imagem/03_Excel.png");
     ImageIcon sair = new ImageIcon("C:/Imagem/08_Fechar.png");
     ImageIcon Limpar = new ImageIcon("C:/Imagem/05_Clear.png");
     ImageIcon Atualizar = new ImageIcon("C:/Imagem/13_Atualizar.png");
     ImageIcon Cadastrar = new ImageIcon("C:/Imagem/14_Cadastrar.png");
     
        btnSalvar.setIcon(inserir);
        btnEditar.setIcon(editar);
        btnCancelar.setIcon(Limpar);
        btnBuscar.setIcon(pesquisar);
    }
    public void importaGrupo(String recebe){
        
        txtDocumento.setText(recebe);
        
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        cmdSituacao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Documento de Caixa");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Documento");

        jLabel2.setText("Descrição:");

        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyPressed(evt);
            }
        });

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });

        cmdSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativado", "Desativado" }));
        cmdSituacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdSituacaoKeyPressed(evt);
            }
        });

        jLabel6.setText("Situação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEditar)
                    .addComponent(btnBuscar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" DOCUMENTO DE CAIXA", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("CADASTRO DOCUMENTO DE CAIXA");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void cancelar(){
        txtDescricao.setText("");
        txtDocumento.setText("");
        cmdSituacao.setSelectedItem("Ativado");
        btnSalvar.setEnabled(true);
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void salvar(){
          String situacao = "0";
        try {
            this.con = database.getConnection();

            Grupo_Produto GRU = new Grupo_Produto();

            GRU.setCodigo(txtDocumento.getText());
            GRU.setDescricao(txtDescricao.getText());

            String GRUCod = GRU.codigo;
            String GRUDescricao = GRU.descricao;
            
            if(cmdSituacao.getSelectedItem()=="Ativado"){
                situacao = "0";
            }else situacao = "1";

            try ( //CRIA CONEXAO COM BANCO - PREPAREDSTATEMENT
                PreparedStatement banco = con.prepareStatement("insert into docrec (docdoc,docdes,docsit) values (?,?,?)")) {

                banco.setString(1, GRUCod);
                banco.setString(2, GRUDescricao);
                banco.setString(3, situacao);

                banco.execute();

            }
            JOptionPane.showMessageDialog(null, "Registro inserido com sucesso!", "Mensagem",
                JOptionPane.INFORMATION_MESSAGE);

            cancelar();
            txtDocumento.requestFocus();
            System.out.println("Gravado!");
            con.close();
            

        } catch (Exception ex) {
            Logger.getLogger(formDocumentoSangrias.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int num = 0;
        String situacao = "0";
        try {
            this.con = database.getConnection();

            Grupo_Produto GRU = new Grupo_Produto();

            GRU.setCodigo(txtDocumento.getText());
            GRU.setDescricao(txtDescricao.getText());

            String GRUCodigo = GRU.codigo;
            String GRUDescricao = GRU.descricao;

             if(cmdSituacao.getSelectedItem()=="Ativado"){
                    situacao = "0";
                }else situacao = "1";
             
            try (PreparedStatement busca = con.prepareStatement("select * from DOCREC")) {

                ResultSet rs = busca.executeQuery();
               
                while(rs.next()){
                    String GRUCod = rs.getString("DOCDOC");

                    if(GRUCod.trim().equals(GRUCodigo)){

                        try (PreparedStatement edit = con.prepareStatement("update DOCREC set DOCDES = '"+GRUDescricao+"',DOCDOC = '"+txtDocumento.getText()+"',docsit = '"+situacao+"' where docdoc = '"+GRUCod+"'")) {
                            edit.executeUpdate();

                        }

                        cancelar();

                        num = 1;
                       
                    }

                }

            }
            if(num==0) JOptionPane.showMessageDialog(null, "NÃO TEM ESSE CÓDIGO CADASTRADO NO BANCO DE DADOS!");
        } catch (Exception ex) {
     //       Logger.getLogger(formDocumentoSangrias.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int num = 0;
        try {
            this.con = database.getConnection();

            Grupo_Produto GRU = new Grupo_Produto();

            GRU.setCodigo(txtDocumento.getText());
            GRU.setNum(txtDescricao.getText());

            String GRUCodigo = GRU.codigo;
            
            

            try (PreparedStatement busca = con.prepareStatement("select * from docrec")) {

                ResultSet rs = busca.executeQuery();

                while(rs.next()){
                    String GRUCod = rs.getString("docdoc");

                    if(GRUCod.trim().equals(GRUCodigo)){

                        String Descrição = rs.getString("docdes");
                        int Situacao = rs.getInt("docsit");
                        
                        txtDocumento.setText(GRUCod);
                        txtDescricao.setText(Descrição);
                        
                        if(Situacao == 0){
                            cmdSituacao.setSelectedItem("Ativado");
                        }else cmdSituacao.setSelectedItem("Desativado");
                        
                        num = 1;
                    }

                }

            }
            if(num==0) JOptionPane.showMessageDialog(null, "NÃO TEM ESSE CÓDIGO CADASTRADO NO BANCO DE DADOS!");

        } catch (Exception ex) {
            Logger.getLogger(formDocumentoSangrias.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyPressed
        if(evt.getKeyCode() == 113){
            new formPesquisaReceita().setVisible(true);
            dispose();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             cmdSituacao.requestFocus();
        }
    }//GEN-LAST:event_txtDocumentoKeyPressed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed

    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void cmdSituacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdSituacaoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             txtDescricao.requestFocus();
        }
    }//GEN-LAST:event_cmdSituacaoKeyPressed

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             salvar();
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDocumentoSangrias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDocumentoSangrias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDocumentoSangrias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDocumentoSangrias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDocumentoSangrias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmdSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables

   
}
