/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoSoftware;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author AraujoRS
 */
public final class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * @throws java.io.FileNotFoundException
     */
    public Login() throws FileNotFoundException {
        initComponents();
        //setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);//Não permite editar o tamanho
        carregarImagens();
        this.setLocationRelativeTo(null);//Centralizar Jframe
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblMsgLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCadeado = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setToolTipText("R@D - Tela de login");

        txtSenha.setText("jPasswordField1");
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadeado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMsgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadeado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMsgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //PARA CHAMAR A CONEXAO
    private Connection con;
    
    public void carregarImagens(){
     ImageIcon usuario = new ImageIcon("C:/Imagem/01_Usuario.png");
     ImageIcon cadeado = new ImageIcon("C:/Imagem/02_Cadeado.png");
     ImageIcon entrar = new ImageIcon("C:/Imagem/04_Login.png");
     ImageIcon login = new ImageIcon("C:/Imagem/10_Login.png");
          
        lblUsuario.setIcon(usuario);
        lblCadeado.setIcon(cadeado);
        lblLogin.setIcon(login);
        btnEntrar.setIcon(entrar);
        
        lblUsuario.setHorizontalAlignment(SwingConstants.CENTER);
        lblCadeado.setHorizontalAlignment(SwingConstants.CENTER);
        lblLogin.setHorizontalAlignment(SwingConstants.CENTER);
        btnEntrar.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        login();
    }//GEN-LAST:event_btnEntrarActionPerformed

    public void login(){
        String tipo;
                if (this.txtLogin.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Login!");
            txtLogin.grabFocus();
            return;
        }
        if (this.txtSenha.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Senha!");
            txtSenha.grabFocus();
            return;
        }

        String nomeLogin = txtLogin.getText();
        String senha = new String(txtSenha.getPassword());
        //Trabalhando com data em java
        Date date = Calendar.getInstance().getTime();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String today = formatter.format(date);

        try {
            this.con = database.getConnection();
            //Statement st = con.createStatement();

            Cliente clienteTabela = new Cliente();
            clienteTabela.setNome(nomeLogin);
            clienteTabela.setSenha(senha);

            String usuario = clienteTabela.getNome();
            String usuarioSenha = clienteTabela.getSenha();

            //PreparedStatement posted = con.prepareStatement("INSERT INTO CCLI(NOME_CLIENTE, END_CLIENTE, COD_CLIENTE) VALUES ('" + resultNome + "')");
            PreparedStatement posted = con.prepareStatement("SELECT * FROM CUSER WHERE "
                    + "(USER_NOME = ?)");
            //+ "and (USER_TIPO = ?)");

            posted.setString(1, usuario);
            //posted.setString(2, usuarioSenha);

            ResultSet rs = posted.executeQuery();

            //rs.beforeFirst(); // move o cursor para o início do result set.
            while (rs.next()) {
                tipo = rs.getString("USER_TIPO");
                String linhaNome = rs.getString("USER_NOME");
                String linhaSenha = rs.getString("USER_SENHA");
                String linhaTipo = rs.getString("USER_TIPO");
                String linhaStatus = rs.getString("USER_STATUS");
                
                lblMsgLogin.setForeground(Color.red);
                lblMsgLogin.setText("Processando dados ...");

                if (!txtLogin.getText().equals(linhaNome)) {
                    JOptionPane.showMessageDialog(null, "USUÁRIO INVÁLIDO!",
                            "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                    txtLogin.grabFocus();
                    txtLogin.selectAll();
                    txtLogin.setSelectionColor(Color.YELLOW);
                    txtLogin.setSelectedTextColor(Color.RED);

                    return;
                }
                //VALIDANDO SENHA
                if (!String.valueOf(senha).equals(linhaSenha)) {
                    JOptionPane.showMessageDialog(null, "SENHA INVÁLIDA!",
                            "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                    txtSenha.grabFocus();
                    txtSenha.selectAll();
                    txtSenha.setSelectionColor(Color.YELLOW);
                    txtSenha.setSelectedTextColor(Color.RED);
                    return;
                }

                if (txtLogin.getText().trim().equals(linhaNome)
                        && String.valueOf(senha).equals(linhaSenha) == true) {
                    JOptionPane.showMessageDialog(null,
                            "ACESSO LIBERADO!" + "\n"
                            + "Usuário: " + txtLogin.getText() + "\n"
                            + "Data: " + today);
                    PreparedStatement banco = con.prepareStatement("update cuser set user_status = 1 where user_nome = '" + txtLogin.getText() + "'");
                    banco.executeUpdate();
                    TelaPrincipal TP = new TelaPrincipal(txtLogin.getText());
                    TelaPrincipal2 TP2 = new TelaPrincipal2(txtLogin.getText());
                    TelaPrincipal3 TP3 = new TelaPrincipal3(txtLogin.getText());
                    if(tipo.trim().equals("M")){
                        TP.setTitle(txtLogin.getText());
                        TP.setVisible(true);
                    }else if(tipo.trim().equals("G")){
                        TP2.setTitle(txtLogin.getText());
                        TP2.setVisible(true);
                    }else if(tipo.trim().equals("U")){
                        TP3.setTitle(txtLogin.getText());
                        TP3.setVisible(true);
                    }
                    con.close();
                    rs.close();
                    posted.close();
                    banco.close();
                    limpar();
                    dispose();//Fecha tela atual
                    return;
                    //new Cadastrar().setVisible(true);//Chama nova tela
                }

            }

        } catch (Exception ex) {
            Logger.getLogger(formCadastra.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "USUÁRIO NÃO CADASTRADO!",
                "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        limpar();
    }
    
    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    public void UPDATE() throws Exception{
        this.con = database.getConnection();
        String sgl = "UPDATE USER SET USER_STATUS='1' WHERE USER_NOME='"+txtLogin.getText()+"'";
        PreparedStatement editar = con.prepareStatement(sgl);
        //editar.setString(4, "1");
        
        int rowsUpdate = editar.executeUpdate();
        if(rowsUpdate > 0){
            System.out.println("Arquivo atualizado com sucesso!");
        }
        editar.close();
        con.close();
    }
        
    public void Inserir() throws Exception{
                //cria objeto
                this.con = database.getConnection();
                Statement st = con.createStatement();
                String sql = "INSERT INTO USER VALUES (4,'1')";
                st.executeUpdate( sql );
                st.close();
                con.close();    
            }
    
    public void limpar(){
            txtLogin.setText("");
            txtSenha.setText("");
            txtLogin.requestFocus();
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCadeado;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMsgLogin;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
